"""Initial migration

Revision ID: 643ce977cf24
Revises: 
Create Date: 2026-03-30 12:39:44.969584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643ce977cf24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_role_hidden_rating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'role_id', 'created_at', name='uq_member_role_created')
    )
    op.create_index(op.f('ix_player_role_hidden_rating_member_id'), 'player_role_hidden_rating', ['member_id'], unique=False)
    op.create_index(op.f('ix_player_role_hidden_rating_role_id'), 'player_role_hidden_rating', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_role_hidden_rating_role_id'), table_name='player_role_hidden_rating')
    op.drop_index(op.f('ix_player_role_hidden_rating_member_id'), table_name='player_role_hidden_rating')
    op.drop_table('player_role_hidden_rating')
    # ### end Alembic commands ###
